---
- name: "Sync katello repository"
  vars:
    organization_name: "Test Organization"
    product_name: "Test Product"
  repository_sync:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs }}"
    organization: "{{ organization_name }}"
    product: "{{ product_name }}"
    repository: "{{ repository | default(omit) }}"
  register: result
  ignore_errors: "{{ expected_fail | default(false) }}"
- assert:
    fail_msg: "Syncing repository failed! (expected_change: True)"
    that:
      - result.changed
  when:
    - expected_fail is not defined or not expected_fail
- assert:
    fail_msg: "Syncing repository took longer or shorter than expected!"
    that:
      - (( result.task.ended_at | replace(' UTC', '') | to_datetime ) - ( result.task.started_at | replace(' UTC', '') | to_datetime )).total_seconds() >= 2
  when:
    - expected_fail is not defined or not expected_fail
    - result.task
- assert:
    fail_msg: "repository_sync didn't fail as expected!"
    that:
      - result is failed
      - expected_fail_msg in result.msg
  when:
    - expected_fail is defined
    - expected_fail
...
